#!/bin/bash
export ANT_HOME=/opt/sw/apache-ant-1.9.2/
export PATH=$PATH:/opt/sw/apache-ant-1.9.2/bin

export M2_HOME=/opt/sw/apache-maven-3.0.5/
export PATH=$PATH:$M2_HOME/bin

export JAVA_HOME=/usr/java/jdk1.7.0_05/
export PATH=$PATH:/usr/java/jdk1.7.0_05/bin

export DERBY_HOME=/opt/sw/db-derby-10.9.1.0-bin/
export PATH=$PATH:/opt/sw/db-derby-10.9.1.0-bin/bin

unset SSH_ASKPASS
